var monday_orz;
monday_orz=2;
var tuesday_orz;
var tuesday_vet;
tuesday_orz=3;
tuesday_vet=1;
var wednesday_orz;
var wednesday_vet;
wednesday_orz=2;
wednesday_vet=4;
var orz;
var vet;
orz="ОРЗ = ";
vet="Ветрянка = ";
var orz_week;
var vet_week;
orz_week=monday_orz + tuesday_orz + wednesday_orz;
vet_week=tuesday_vet + wednesday_vet;
orz + orz_week;
vet + vet_week;